// <auto-generated />
using System;
using Hookline.Modules.YouTubeComments.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hookline.Modules.YouTubeComments.Migrations
{
    [DbContext(typeof(YouTubeCommentsDbContext))]
    [Migration("20260618113724_AddCommentDailyStats")]
    partial class AddCommentDailyStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("youtube_comments")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.ChannelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CommentsSinceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("comments_since_utc");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency");

                    b.Property<bool>("IncludeReplies")
                        .HasColumnType("boolean")
                        .HasColumnName("include_replies");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<string>("ReplySweepFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reply_sweep_frequency");

                    b.Property<int>("ReplyWindowDays")
                        .HasColumnType("integer")
                        .HasColumnName("reply_window_days");

                    b.Property<Guid>("SlackChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("slack_channel_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("YouTubeChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("youtube_channel_id");

                    b.HasKey("Id")
                        .HasName("pk_channel_mappings");

                    b.HasIndex("SlackChannelId")
                        .HasDatabaseName("ix_channel_mappings_slack_channel_id");

                    b.HasIndex("YouTubeChannelId", "SlackChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_channel_mappings_youtube_channel_id_slack_channel_id");

                    b.ToTable("channel_mappings", "youtube_comments");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.CommentDailyStat", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("MappingId")
                        .HasColumnType("uuid")
                        .HasColumnName("mapping_id");

                    b.Property<int>("AlreadyGone")
                        .HasColumnType("integer")
                        .HasColumnName("already_gone");

                    b.Property<string>("ChannelTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("channel_title");

                    b.Property<int>("EnrichedCount")
                        .HasColumnType("integer")
                        .HasColumnName("enriched_count");

                    b.Property<int>("Forwarded")
                        .HasColumnType("integer")
                        .HasColumnName("forwarded");

                    b.Property<int>("Rejected")
                        .HasColumnType("integer")
                        .HasColumnName("rejected");

                    b.Property<int>("Removed")
                        .HasColumnType("integer")
                        .HasColumnName("removed");

                    b.Property<int>("Replies")
                        .HasColumnType("integer")
                        .HasColumnName("replies");

                    b.Property<long>("SumLikes")
                        .HasColumnType("bigint")
                        .HasColumnName("sum_likes");

                    b.HasKey("Date", "MappingId")
                        .HasName("pk_comment_daily_stats");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_comment_daily_stats_date");

                    b.ToTable("comment_daily_stats", "youtube_comments");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.CommentModeration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MappingId")
                        .HasColumnType("uuid")
                        .HasColumnName("mapping_id");

                    b.Property<string>("SlackUserId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slack_user_id");

                    b.Property<string>("SlackUserName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slack_user_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_comment_moderations");

                    b.HasIndex("MappingId", "CommentId")
                        .IsUnique()
                        .HasDatabaseName("ix_comment_moderations_mapping_id_comment_id");

                    b.ToTable("comment_moderations", "youtube_comments");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.PendingDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<Guid>("MappingId")
                        .HasColumnType("uuid")
                        .HasColumnName("mapping_id");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("ParentCommentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_comment_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_pending_deliveries");

                    b.HasIndex("MappingId")
                        .HasDatabaseName("ix_pending_deliveries_mapping_id");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_pending_deliveries_next_attempt_at");

                    b.ToTable("pending_deliveries", "youtube_comments");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.ProcessedComment", b =>
                {
                    b.Property<Guid>("MappingId")
                        .HasColumnType("uuid")
                        .HasColumnName("mapping_id");

                    b.Property<string>("CommentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("comment_id");

                    b.Property<string>("AuthorChannelUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("author_channel_url");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_name");

                    b.Property<int?>("CommentLength")
                        .HasColumnType("integer")
                        .HasColumnName("comment_length");

                    b.Property<long?>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<string>("ParentCommentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_comment_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SlackMessageTs")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slack_message_ts");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("video_id");

                    b.Property<string>("VideoTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("video_title");

                    b.HasKey("MappingId", "CommentId")
                        .HasName("pk_processed_comments");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_processed_comments_processed_at");

                    b.ToTable("processed_comments", "youtube_comments");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.SlackChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("SlackChannelId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slack_channel_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_slack_channels");

                    b.HasIndex("WorkspaceId", "SlackChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_slack_channels_workspace_id_slack_channel_id");

                    b.ToTable("slack_channels", "youtube_comments");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.YouTubeChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Handle")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("handle");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("YouTubeChannelId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("youtube_channel_id");

                    b.HasKey("Id")
                        .HasName("pk_youtube_channels");

                    b.HasIndex("YouTubeChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_youtube_channels_youtube_channel_id");

                    b.ToTable("youtube_channels", "youtube_comments");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.ChannelMapping", b =>
                {
                    b.HasOne("Hookline.Modules.YouTubeComments.Domain.SlackChannel", "SlackChannel")
                        .WithMany("Mappings")
                        .HasForeignKey("SlackChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_mappings_slack_channels_slack_channel_id");

                    b.HasOne("Hookline.Modules.YouTubeComments.Domain.YouTubeChannel", "YouTubeChannel")
                        .WithMany("Mappings")
                        .HasForeignKey("YouTubeChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_mappings_you_tube_channels_you_tube_channel_id");

                    b.Navigation("SlackChannel");

                    b.Navigation("YouTubeChannel");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.CommentModeration", b =>
                {
                    b.HasOne("Hookline.Modules.YouTubeComments.Domain.ChannelMapping", null)
                        .WithMany()
                        .HasForeignKey("MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_moderations_channel_mappings_mapping_id");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.PendingDelivery", b =>
                {
                    b.HasOne("Hookline.Modules.YouTubeComments.Domain.ChannelMapping", "Mapping")
                        .WithMany()
                        .HasForeignKey("MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pending_deliveries_channel_mappings_mapping_id");

                    b.Navigation("Mapping");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.ProcessedComment", b =>
                {
                    b.HasOne("Hookline.Modules.YouTubeComments.Domain.ChannelMapping", "Mapping")
                        .WithMany("ProcessedComments")
                        .HasForeignKey("MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processed_comments_channel_mappings_mapping_id");

                    b.Navigation("Mapping");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.ChannelMapping", b =>
                {
                    b.Navigation("ProcessedComments");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.SlackChannel", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeComments.Domain.YouTubeChannel", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
