// <auto-generated />
using System;
using Hookline.Modules.YouTubeUploads.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hookline.Modules.YouTubeUploads.Migrations
{
    [DbContext(typeof(YouTubeUploadsDbContext))]
    partial class YouTubeUploadsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("youtube_uploads")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hookline.Modules.YouTubeUploads.Domain.ChannelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GoogleAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("google_account_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("SlackChannelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slack_channel_id");

                    b.Property<string>("SlackChannelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slack_channel_name");

                    b.Property<Guid>("SlackWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("slack_workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_channel_mappings");

                    b.HasIndex("SlackChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_channel_mappings_slack_channel_id");

                    b.ToTable("channel_mappings", "youtube_uploads");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeUploads.Domain.GoogleAccountBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YouTubeChannelId")
                        .HasColumnType("text")
                        .HasColumnName("you_tube_channel_id");

                    b.HasKey("Id")
                        .HasName("pk_google_account_bindings");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_google_account_bindings_account_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_google_account_bindings_project_id");

                    b.HasIndex("YouTubeChannelId")
                        .HasDatabaseName("ix_google_account_bindings_you_tube_channel_id");

                    b.ToTable("google_account_bindings", "youtube_uploads");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeUploads.Domain.GoogleProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedClientSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_client_secret");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_google_projects");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_google_projects_client_id");

                    b.ToTable("google_projects", "youtube_uploads");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeUploads.Domain.JobStateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("FromState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_state");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_state");

                    b.HasKey("Id")
                        .HasName("pk_job_state_history");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_state_history_job_id");

                    b.ToTable("job_state_history", "youtube_uploads");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeUploads.Domain.SlackChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsMember")
                        .HasColumnType("boolean")
                        .HasColumnName("is_member");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SlackChannelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slack_channel_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_slack_channels");

                    b.HasIndex("SlackChannelId")
                        .HasDatabaseName("ix_slack_channels_slack_channel_id");

                    b.HasIndex("WorkspaceId", "SlackChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_slack_channels_workspace_id_slack_channel_id");

                    b.ToTable("slack_channels", "youtube_uploads");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeUploads.Domain.UploadJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BytesTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_total");

                    b.Property<long>("BytesTransferred")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_transferred");

                    b.Property<bool?>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DownloadStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("download_started_at");

                    b.Property<string>("DriveFileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("drive_file_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("GoogleAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("google_account_id");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text")
                        .HasColumnName("hangfire_job_id");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<int>("QuotaUnitsCharged")
                        .HasColumnType("integer")
                        .HasColumnName("quota_units_charged");

                    b.Property<bool>("RequiresConfirmation")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_confirmation");

                    b.Property<string>("SlackChannelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slack_channel_id");

                    b.Property<string>("SlackEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slack_event_id");

                    b.Property<string>("SlackMessageTs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slack_message_ts");

                    b.Property<string>("SlackUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slack_user_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("ThumbnailMimeType")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_mime_type");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("UploadStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_started_at");

                    b.Property<string>("YouTubeUrl")
                        .HasColumnType("text")
                        .HasColumnName("you_tube_url");

                    b.Property<string>("YouTubeVideoId")
                        .HasColumnType("text")
                        .HasColumnName("you_tube_video_id");

                    b.HasKey("Id")
                        .HasName("pk_upload_jobs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_upload_jobs_created_at");

                    b.HasIndex("SlackEventId")
                        .HasDatabaseName("ix_upload_jobs_slack_event_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_upload_jobs_state");

                    b.HasIndex("SlackChannelId", "UpdatedAt")
                        .HasDatabaseName("ix_upload_jobs_slack_channel_id_updated_at");

                    b.ToTable("upload_jobs", "youtube_uploads");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeUploads.Domain.GoogleAccountBinding", b =>
                {
                    b.HasOne("Hookline.Modules.YouTubeUploads.Domain.GoogleProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_google_account_bindings_google_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeUploads.Domain.JobStateHistory", b =>
                {
                    b.HasOne("Hookline.Modules.YouTubeUploads.Domain.UploadJob", "Job")
                        .WithMany("History")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_state_history_upload_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Hookline.Modules.YouTubeUploads.Domain.UploadJob", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
