import {
  Activity,
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  Ban,
  Bell,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleX,
  Clock,
  CloudUpload,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileVideo,
  Filter,
  Flag,
  Gauge,
  Hash,
  Home,
  Inbox,
  Key,
  Link2,
  Lock,
  LogOut,
  Mail,
  MessageSquare,
  MoreHorizontal,
  Moon,
  Pause,
  Play,
  Plug,
  Plus,
  RefreshCw,
  Reply,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  SlidersHorizontal,
  Star,
  Sun,
  Trash2,
  TriangleAlert,
  User,
  Users,
  Video,
  X,
  Zap,
} from "lucide-react";

import { GoogleIcon, LinkedinIcon, SlackIcon, YoutubeIcon } from "@/components/brand-icons";
import type { IconType } from "@/lib/platforms";

/** Resolve the prototype's string icon names (used in mock data) to glyphs. */
const ICONS: Record<string, IconType> = {
  home: Home,
  messageSquare: MessageSquare,
  hash: Hash,
  uploadCloud: CloudUpload,
  cloudUpload: CloudUpload,
  plug: Plug,
  slack: SlackIcon,
  youtube: YoutubeIcon,
  google: GoogleIcon,
  linkedin: LinkedinIcon,
  key: Key,
  settings: Settings,
  scrollText: ScrollText,
  search: Search,
  sun: Sun,
  moon: Moon,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronsUpDown: ChevronsUpDown,
  moreHorizontal: MoreHorizontal,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowUpDown: ArrowUpDown,
  plus: Plus,
  x: X,
  check: Check,
  trash: Trash2,
  pause: Pause,
  play: Play,
  refresh: RefreshCw,
  download: Download,
  fileVideo: FileVideo,
  bell: Bell,
  activity: Activity,
  circleCheck: CircleCheck,
  circleAlert: CircleAlert,
  circleX: CircleX,
  clock: Clock,
  filter: Filter,
  calendar: Calendar,
  inbox: Inbox,
  lock: Lock,
  user: User,
  users: Users,
  logout: LogOut,
  externalLink: ExternalLink,
  link: Link2,
  zap: Zap,
  thumbsUp: Star,
  flag: Flag,
  shield: Shield,
  shieldAlert: ShieldAlert,
  alertTriangle: TriangleAlert,
  eye: Eye,
  eyeOff: EyeOff,
  mail: Mail,
  reply: Reply,
  gauge: Gauge,
  building: Building2,
  creditCard: CreditCard,
  sliders: SlidersHorizontal,
  star: Star,
  copy: Copy,
  video: Video,
  ban: Ban,
};

export function iconByName(name: string): IconType {
  return ICONS[name] ?? CircleAlert;
}
